---
- name: exporters | consul | Create consul config and restart
  template:
    src: consul_template.j2
    dest: "{{ consul_path }}/{{ item.consul.file | d(item.name + '-' + ansible_hostname + '.json') }}"
    owner: root
    mode: 0644
    backup: no
  delegate_to: "{{ consul_host }}"
  notify:
    - restart consul
